Section "ServerLayout"
    Identifier "layout"
    Screen "screen"
EndSection

Section "Device"
    Identifier "fbdev"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "monitor"
    HorizSync 28-80
    VertRefresh 43-76
EndSection

Section "Screen"
    Identifier "screen"
    Device "fbdev"
    Monitor "monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x720"
    EndSubSection
EndSection

Section "InputDevice"
    Identifier "touchscreen"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
    Option "Emulate3Buttons" "true"
EndSection
